// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxqqjmnlnazjvdagxirw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cXFqbW5sbmF6anZkYWd4aXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Njg2MzEsImV4cCI6MjA3MDE0NDYzMX0.Q1-RJLTDyk4lerel3jWjuyKstQhPQvyMrxhk7r7vsvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});